APP_TOKEN: token
PARTIALS:
  - MESSAGE
  - CHANNEL
  - REACTION
INTENTS:
  - GUILDS
  - GUILD_MEMBERS
  - GUILD_BANS
  - GUILD_EMOJIS_AND_STICKERS
  - GUILD_INTEGRATIONS
  - GUILD_WEBHOOKS
  - GUILD_INVITES
  - GUILD_VOICE_STATES
  - GUILD_PRESENCES
  - GUILD_MESSAGES
  - GUILD_MESSAGE_REACTIONS
  - GUILD_MESSAGE_TYPING
  - DIRECT_MESSAGES
  - DIRECT_MESSAGE_REACTIONS
  - DIRECT_MESSAGE_TYPING
STORAGE:
  DRIVER: sqlite3
  PATH: ./database.sql